### ISSUE TITLE
Time complexity of the algorithm

### ISSUE THREAD

**Issue by Eli-Black-Work** [sindresorhus/array-differ#10]
Would you be okay with adding something to the README stating what the time complexity of the algorithm is? My understanding from looking at the code is that it's O(n log n), but I'm not sure if that's correct.

Thanks :)

**Comment by sindresorhus** [comment]
Happy to document it, but I don't know the answer.

**Comment by Eli-Black-Work** [comment]
Haha, okay, got it. Well, hopefully someone else who is algorithmically inclined will come along and see this :)

**Comment by wilsonwangdev** [comment]
> Haha, okay, got it. Well, hopefully someone else who is algorithmically inclined will come along and see this :)

If arrayOne's length is a and arrayTwo's length is b, isn't it the time complexity is O(ab)?

1. We need at least iterate arrayOne a times and generally iterate arrayTwo b/2 times as an average situation.
2. The iteration of arrayTwo is in each arrayOne's iteration, so the time complexity is O(a * b/2).
3. The constant level factor should be ignored.
4. As a result, the answer is O(ab)

**Comment by dotlambda** [comment]
If you call `arrayDiffer(a, b)` and `m = a.length`, `n = b.length`, then turning `b` into a set takes `O(n * log n)` because inserting a single element into the set takes `O(n)`, and filtering `a` takes `O(m * log n)`. To summarize, the complexity is `O(max(m, n) * log n)`. But that's a worst-case analysis which might be irrelevant in real life.
